stages:
  - test_fast
  - test_integration
  - build
  - deploy

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx2048m"
  SPRING_PROFILES_ACTIVE: "test"
  TESTCONTAINERS_RYUK_DISABLED: "true"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2

services:
  - name: docker:dind
    command: ["--tls=false"]

cache:
  key: gradle-cache
  paths:
    - backend/.gradle/wrapper
    - backend/.gradle/caches

unit_tests:
  stage: test_fast
  before_script:
    - git remote set-url origin "https://gitlab-ci-token:${CI_JOB_TOKEN}@git.fhict.nl/I548631/drawduel.git"
    - cd backend
  script:
    - echo "⚡ Running unit tests..."
    - gradle :tests:test --tests "*ServiceTest" --tests "*UseCaseTest" --rerun-tasks
  tags: [tests]
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/
  only:
    - dev
    - main
    - merge_requests

integration_tests:
  stage: test_integration
  before_script:
    - cd backend/tests
    - export $(grep -v '^#' .env | xargs)
    - cd ..
  script:
    - echo "🐘 Running integration + controller tests with Testcontainers..."
    - gradle :tests:test --tests "*IntegrationTest" --tests "*ControllerTest" --rerun-tasks
  tags: [tests]
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/
  needs:
    - job: unit_tests
      artifacts: false
  only:
    - dev
    - main
    - merge_requests

build_stage:
  stage: build
  before_script:
    - cd backend
  script:
    - echo "🏗️ Building backend JAR..."
    - gradle clean build -x test
  tags: [build]
  artifacts:
    paths:
      - backend/build/libs/
    expire_in: 1 week
  needs:
    - job: integration_tests
      artifacts: false
  only:
    - dev
    - main

deploy:
  tags: build #no deploy task in the runner
  stage: deploy
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""

  script:
    - echo "Logging in to Docker Hub..."
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

    - echo "📦 Building Docker images..."
    - docker build -t $DOCKERHUB_USERNAME/drawduel-backend:latest backend
    - docker build -t $DOCKERHUB_USERNAME/drawduel-frontend:latest frontend

    - echo "⬆️ Pushing images to Docker Hub..."
    - docker push $DOCKERHUB_USERNAME/drawduel-backend:latest
    - docker push $DOCKERHUB_USERNAME/drawduel-frontend:latest

  needs:
    - job: build_stage
      artifacts: true

  only:
    - main
    - dev
