plugins {
  id 'java'
  id 'org.springframework.boot' version '3.5.5'
  id "io.spring.dependency-management" version "1.1.7"
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(":application")
  implementation project(":domain")

  implementation("org.projectlombok:lombok:1.18.30")

  implementation "org.springframework.boot:spring-boot-starter"
  implementation "org.springframework.boot:spring-boot-starter-web"
  implementation "org.springframework.boot:spring-boot-starter-validation"
  implementation "org.springframework.boot:spring-boot-starter-actuator"
  implementation "org.springframework.boot:spring-boot-starter-websocket"
  implementation "org.springframework.boot:spring-boot-starter-data-jpa"

  implementation 'org.springframework.boot:spring-boot-starter-security'
  implementation 'org.springframework.boot:spring-boot-starter-validation'
  implementation "org.springframework.security:spring-security-crypto"

  implementation "org.postgresql:postgresql:42.7.3"
  implementation("org.flywaydb:flyway-database-postgresql")

  implementation 'org.springframework.boot:spring-boot-starter-websocket'
  implementation 'org.springframework.boot:spring-boot-starter-web'

  compileOnly 'org.projectlombok:lombok:1.18.34'
  annotationProcessor 'org.projectlombok:lombok:1.18.34'
  testCompileOnly 'org.projectlombok:lombok:1.18.34'
  testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'

  implementation "org.mapstruct:mapstruct:1.6.2"
  annotationProcessor "org.mapstruct:mapstruct-processor:1.6.2"

  implementation group: 'com.cloudinary', name: 'cloudinary-core', version: '2.3.2'
  implementation 'com.cloudinary:cloudinary-http5:2.3.2'

  testImplementation "org.springframework.boot:spring-boot-starter-test"
}

bootRun {
  if (project.hasProperty('debug')) {
    jvmArgs = [
        "-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005"
    ]
  }

  systemProperty "spring.profiles.active", "local"

  def envFile = file(".env.local")

  if (envFile.exists()) {
      println "Loading environment variables from .env.local"
      envFile.eachLine { line ->
          if (line && !line.startsWith("#") && line.contains("=")) {
              def (key, value) = line.split("=", 2)
              environment key.trim(), value.trim()
              println " -> loaded $key"
          }
      }
  } else {
      println "WARNING: .env.local not found"
  }
}
