spring:
  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://localhost:5432/drawduel
    username: drawduel
    password: pass_for_drawduel_db@77
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta.persistence.schema-generation.scripts.action: create
      jakarta.persistence.schema-generation.scripts.create-target: build/generated-schema.sql
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework: INFO
